# GoReleaser configuration for lissto CLI
# Visit https://goreleaser.com for documentation
#
# Version: This configuration is tested with GoReleaser v2.13.0
# To maintain compatibility, both the GitHub Action and local development
# should use this version to avoid breaking changes.

version: 2

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: lissto
    main: ./main.go
    binary: lissto
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/lissto-dev/cli/cmd.Version={{.Version}}
      - -X github.com/lissto-dev/cli/cmd.Commit={{.Commit}}
      - -X github.com/lissto-dev/cli/cmd.Date={{.Date}}

archives:
  - id: default
    ids:
      - lissto
    files:
      - README.md
      - MCP.md

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
      - Merge pull request
      - Merge branch
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999

brews:
  - name: lissto
    repository:
      owner: lissto-dev
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/lissto-dev/cli"
    description: "Lissto CLI - Deploy and manage your stacks on Kubernetes"
    license: "MIT"
    test: |
      system "#{bin}/lissto", "--version"
    install: |
      bin.install "lissto"
      generate_completions_from_executable(bin/"lissto", "completion", shells: [:bash, :zsh, :fish])

release:
  github:
    owner: lissto-dev
    name: cli
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## Lissto CLI {{ .Tag }}

    Install with Homebrew:
    ```bash
    brew install lissto-dev/tap/lissto
    ```

    Or download the binary for your platform below.

